### ISSUE TITLE
Feedback: First Challenge Submission

### ISSUE THREAD

**Issue by Anisha7** [edwintcloud/cs1.3_exercises#1]
Good job on completing the submission! Here are a few things to work on for full credit:

- **Binary search**: recursive function currently stops before checking the last item in your array! Check your base case to make sure you stop _after_ checking the last item. (You’re only off by one). 
- **String Algorithms Refactoring**: I see that  you refactored your contains function. However, find_index and find_all_indexes has duplicate code. Try to refactor it such that there is no duplicate code in your program.
- **Missing**: Annotations for String Algorithms Time and Space complexity

**Comment by edwintcloud** [comment]
Fixed f3d7d1a
